# Generated by Django 4.1.5 on 2023-01-31 22:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0006_alter_post_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='likes',
            new_name='likes_post',
        ),
        migrations.RemoveField(
            model_name='post',
            name='reply',
        ),
        migrations.AddField(
            model_name='post',
            name='saves_posts',
            field=models.ManyToManyField(blank=True, related_name='blog_posts_save', to=settings.AUTH_USER_MODEL, verbose_name='Сохранённые посты пользователя'),
        ),
    ]
