# Generated by Django 4.1.6 on 2023-02-02 23:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0007_rename_likes_post_likes_post_remove_post_reply_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes_post',
            field=models.ManyToManyField(blank=True, related_name='post_likes', to=settings.AUTH_USER_MODEL, verbose_name='Лайки'),
        ),
    ]
