# Generated by Django 4.1.6 on 2023-02-03 12:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discussions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussions',
            name='likes_discussions',
        ),
        migrations.RemoveField(
            model_name='discussions',
            name='saves_discussions',
        ),
        migrations.AddField(
            model_name='discussions',
            name='likes_discussion',
            field=models.ManyToManyField(blank=True, related_name='discussion_likes', to=settings.AUTH_USER_MODEL, verbose_name='Лайки'),
        ),
        migrations.AddField(
            model_name='discussions',
            name='saves_discussion',
            field=models.ManyToManyField(blank=True, related_name='blog_discussion_save', to=settings.AUTH_USER_MODEL, verbose_name='Сохранённые посты пользователя'),
        ),
    ]
